[simulation]
integrator = "respa"
respa_inner = 10
n_steps = 3000                             # total simulation steps
n_print = 200                              # output trajectory data every n steps
n_flush = 1
time_step = 0.01                           # time step in ps
box_size = [19.69551, 19.69551, 19.46156]  # simulation box size in nm
start_temperature = 303                    # generate starting temperature in K
target_temperature = 303                   # thermostat temperature in K
tau = 0.1                                  # thermostat coupling strength in ps
hamiltonian = "defaultwithchi"             # interaction energy functional
kappa = 0.05                               # compressibility in mol/kJ
domain_decomposition = 10001
cancel_com_momentum = true
max_molecule_size = 40
thermostat_coupling_groups = [
  ["PHI", "ALA"],
  ["N", "P", "G", "C", "D"],
  ["W"],
]
dielectric_const = 80.0

[field]
mesh_size = [24, 24, 24]           # FFT grid size
sigma = 0.4                        # filtering length scale in nm
chi = [
  ["C",   "W",   35.00],
  ["G",   "C",   14.61],
  ["N",   "W",   -2.46],
  ["G",   "W",    9.07],
  ["N",   "P",   -3.40],
  ["P",   "G",    8.45],
  ["N",   "G",    4.92],
  ["P",   "C",   12.52],
  ["P",   "W",   -1.27],
  ["N",   "C",   14.39],
  ["N",   "D",    7.20],
  ["P",   "D",   11.70],
  ["G",   "D",    6.30],
  ["C",   "D",    0.00],
  ["W",   "D",   23.25],
  ["PHI", "C",   35.00],
  ["ALA", "C",    0.00],
  ["PHI", "W",    0.00],
  ["ALA", "W",   35.00],
  ["C",   "PHI", 35.00],
  ["N",   "PHI", -2.46],
  ["G",   "PHI",  9.07],
  ["P",   "PHI", -1.27],
  ["PHI", "D",   23.25],
  ["ALA", "D",    0.00],
  ["ALA", "W",   35.00],
  ["G",   "ALA", 14.61],
  ["P",   "ALA", 12.52],
  ["N",   "ALA", 14.39],
  ["ALA", "D",    0.00],
  ["ALA", "PHI",  0.00],
]

[bonds]
bonds = [
  ["N",   "P",   0.47, 1250.0],
  ["P",   "G",   0.47, 1250.0],
  ["G",   "G",   0.37, 1250.0],
  ["G",   "C",   0.47, 1250.0],
  ["C",   "C",   0.47, 1250.0],
  ["C",   "D",   0.47, 1250.0],
  ["ALA", "ALA", 0.31, 12500.0],
  ["ALA", "PHI", 0.31, 12500.0],
  ["PHI", "PHI", 0.31, 12500.0],
]
angle_bonds = [
  ["P", "G", "G", 120.0, 25.0],
  ["P", "G", "C", 180.0, 25.0],
  ["G", "C", "C", 180.0, 25.0],
  ["C", "C", "C", 180.0, 25.0],
  ["C", "D", "C", 120.0, 45.0],
  ["D", "C", "C", 180.0, 25.0],
]
dihedrals = [
  [
    ["PHI", "PHI", "PHI", "ALA"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["PHI", "PHI", "ALA", "ALA"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["PHI", "ALA", "ALA", "ALA"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["ALA", "ALA", "ALA", "ALA"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["ALA", "ALA", "ALA", "PHI"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["ALA", "ALA", "PHI", "PHI"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
  [
    ["ALA", "PHI", "PHI", "PHI"],
    [
      [-1],
      [449.08790868, 610.2408724, -544.48626121, 251.59427866, -84.9918564],
      [0.08, 0.46, 1.65, -0.96, 0.38],
    ],
    [1.0]
  ],
]
