[simulation]
integrator = "respa"
respa_inner = 10
n_steps = 3000                    # total simulation steps
n_print = 1500                    # output trajectory data every n steps
n_flush = 1
time_step = 0.01                  # time step in ps
box_size = [8.3, 8.3, 8.3]        # simulation box size in nm
start_temperature = 298           # generate starting temperature in K
target_temperature = 298          # thermostat temperature in K
tau = 0.1                         # thermostat coupling strength in ps
hamiltonian = "defaultwithchi"    # interaction energy functional
kappa = 0.1                       # compressibility in mol/kJ
domain_decomposition = 10000
cancel_com_momentum = true
max_molecule_size = 5
thermostat_coupling_groups = [
  ["S", "C"],
  ["W", "Na"],
]
dielectric_const = 45.0
coulombtype = "PIC_Spectral"

[field]
mesh_size = [64, 64, 64]          # FFT grid size
sigma = 0.5                       # filtering length scale in nm
chi = [
  ["S", "C",  13.50],
  ["S", "Na",  0.00],
  ["S", "W",  -3.60],
  ["C", "Na", 13.50],
  ["C", "W",  33.75],
  ["W", "Na",  0.00],
]

[bonds]
bonds = [
  ["S",   "C",   0.50, 1250.0],
  ["C",   "C",   0.50, 1250.0],
]
angle_bonds = [
  ["S", "C", "C", 170.0, 25.0],
  ["C", "C", "C", 180.0, 25.0],
]
